version: "3.8"

services:
  mysql-go-database:
    image: mysql:latest
    container_name: mysql-go-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
  postgres-go-database:
    image: postgres:latest
    container_name: postgres-go-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ~/Downloads/dvdrental.tar:/var/lib/dvdrental
