version: "3.8"

services:
  mysql-go-database:
    image: mysql:latest
    container_name: mysql-go-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./sample/mysql:/docker-entrypoint-initdb.d
  postgres-go-database:
    image: postgres:latest
    container_name: postgres-go-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./sample/postgres:/docker-entrypoint-initdb.d
